#!/usr/bin/env python3
"""Render a Fastfetch profile on one shared terminal grid.

The ASCII cells are sampled from assets/avatar.png, the GitHub profile photo
from https://avatars.githubusercontent.com/u/57810766?v=4 (2026-09-05).
Each portrait row occupies exactly one metadata row, using the same font size,
character width and baseline. Run from the repository root with
Python 3 and Pillow: python3 scripts/render_profile.py.
"""

from __future__ import annotations

import argparse
import html
from pathlib import Path

from PIL import Image, ImageEnhance, ImageOps


BACKGROUND = "#161b22"
TEXT = "#c9d1d9"
MUTED = "#697787"
KEY = "#ffa657"
VALUE = "#a5d6ff"

RIGHT_ROWS: tuple[tuple[str, str, str], ...] = (
    ("section", "Who am I?", ""),
    ("meta", "Name", "Thomas Fairhurst"),
    ("meta", "Role", "Co-founder & CTO at Leadlord"),
    ("meta", "Building", "Compliant marketing, fast & affordable"),
    ("meta", "Education", "McGill CS → Imperial Advanced Computing"),
    ("blank", "", ""),
    ("meta", "Previously", "PhoneHost — AI Host for Restaurants"),
    ("meta", "Open Source", "toks, agentdictate"),
    ("meta", "Following", "Bun · GPUI · SpacetimeDB · Omarchy"),
    ("meta", "Principle", "Keep it simple, stupid."),
    ("meta", "Offline", "Poker · Gym"),
    ("blank", "", ""),
    ("section", "Contact", ""),
    ("meta", "GitHub", "github.com/Luzivog"),
    ("meta", "Website", "thomas-fairhurst.com"),
    ("meta", "LinkedIn", "linkedin.com/in/thomas-fht"),
    ("meta", "X", "x.com/luzivog"),
    ("blank", "", ""),
    ("section", "Projects", ""),
    ("meta", "Leadlord", "Compliant marketing campaigns"),
    ("meta", "PhoneHost", "AI Host for Restaurants"),
    ("meta", "toks", "Local AI coding usage tracker"),
    ("meta", "agentdictate", "Native Linux voice dictation"),
)


FONT_SIZE = 16
CELL_WIDTH = 9.64
ROW_HEIGHT = 20
ROW_START = 60
PORTRAIT_X = 24
PORTRAIT_COLUMNS = 42
RIGHT_X = 456
VALUE_X = RIGHT_X + 14 * CELL_WIDTH
WIDTH = 1006
HEIGHT = ROW_START + (len(RIGHT_ROWS) - 1) * ROW_HEIGHT + 30


def text(x: float, y: float, content: str, color: str, extra: str = "") -> str:
    return (f'<text x="{x:g}" y="{y:g}" fill="{color}"{extra}>'
            f'{html.escape(content)}</text>')


def metadata_svg() -> str:
    """Give every label and value an explicit, stable starting column."""
    rendered: list[str] = []
    for index, (kind, label, value) in enumerate(RIGHT_ROWS):
        y = ROW_START + index * ROW_HEIGHT
        if kind == "section":
            rendered.append(text(RIGHT_X, y, label, TEXT))
        elif kind == "meta":
            rendered.append(text(RIGHT_X, y, label + ":", KEY,
                                 ' font-weight="bold"'))
            rendered.append(text(VALUE_X, y, value, VALUE))
    return "\n".join(rendered)


def portrait_svg(path: Path) -> str:
    """Sample the actual avatar into colored glyphs, without a photo underlay."""
    row_count = len(RIGHT_ROWS)
    with Image.open(path) as source:
        source = ImageOps.exif_transpose(source).convert("RGB")
        # Normalized crop keeps the cap, face and shoulders at their real aspect.
        width, height = source.size
        left, top = width * .14, height * .165
        aspect = PORTRAIT_COLUMNS * CELL_WIDTH / (row_count * ROW_HEIGHT)
        crop = source.crop((left, top, left + (height - top) * aspect, height))
        sampled = crop.resize((PORTRAIT_COLUMNS, row_count), Image.Resampling.LANCZOS)
        luminance = sampled.convert("L")
        colors = ImageEnhance.Color(sampled).enhance(1.3)

    ramp = " .,:;irsXA253hMHGS#9B&@"
    rendered: list[str] = []
    for row in range(row_count):
        y = ROW_START + row * ROW_HEIGHT
        cells: list[str] = []
        for column in range(PORTRAIT_COLUMNS):
            light = luminance.getpixel((column, row))
            if light < 24:
                continue
            glyph = ramp[min(len(ramp) - 1, int((light / 255) ** .8 * (len(ramp) - 1)))]
            rgb = colors.getpixel((column, row))
            color = "#" + "".join(f"{min(255, round(channel * 1.1 + 24)):02x}" for channel in rgb)
            x = PORTRAIT_X + column * CELL_WIDTH
            cells.append(f'<tspan x="{x:g}" fill="{color}">{html.escape(glyph)}</tspan>')
        rendered.append(f'<text y="{y:g}">{"".join(cells)}</text>')
    return '<g font-weight="bold" aria-hidden="true">' + "\n".join(rendered) + '</g>'


def profile_svg(portrait_path: Path) -> str:
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/render_profile.py from the GitHub profile avatar. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {WIDTH} {HEIGHT}" width="{WIDTH}" height="{HEIGHT}" font-family="'DejaVu Sans Mono',Consolas,monospace" font-size="{FONT_SIZE}" role="img" aria-labelledby="title description">
  <title id="title">Thomas Fairhurst — GitHub profile</title>
  <desc id="description">A Fastfetch-style profile with an ASCII portrait made from Thomas's GitHub avatar. Co-founder and CTO at Leadlord. Open-source author of toks and agentdictate.</desc>
  <rect width="{WIDTH}" height="{HEIGHT}" fill="{BACKGROUND}" rx="15"/>
  <text x="24" y="28" fill="{TEXT}"><tspan fill="{VALUE}">~</tspan><tspan fill="{MUTED}"> › </tspan>fastfetch</text>
  {portrait_svg(portrait_path)}
  <g>{metadata_svg()}</g>
</svg>
'''


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--portrait", default=Path("assets/avatar.png"), type=Path)
    parser.add_argument("--output", default=Path("assets/profile-grid.svg"), type=Path)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(profile_svg(args.portrait), encoding="utf-8")


if __name__ == "__main__":
    main()
