#!/usr/bin/env python3
"""Render Thomas Fairhurst's Neofetch-style GitHub profile card.

The curated transparent PNG is the canonical ASCII portrait artwork. This
script embeds it beside the deterministic 25-row terminal profile.
"""

from __future__ import annotations

import argparse
import base64
import html
from dataclasses import dataclass
from pathlib import Path

from PIL import Image


@dataclass(frozen=True)
class Palette:
    background: str
    text: str
    connector: str
    key: str
    value: str


PALETTE = Palette(
    background="#161b22",
    text="#c9d1d9",
    connector="#616e7f",
    key="#ffa657",
    value="#a5d6ff",
)

RIGHT_ROWS: tuple[tuple[str, str, str], ...] = (
    ("prompt", "~", "fastfetch"),
    ("meta", "Name", "Thomas Fairhurst"),
    ("meta", "Role", "Co-founder & CTO at Leadlord"),
    ("meta", "Building", "Compliant campaigns, fast & affordable"),
    ("meta", "Education", "McGill CS → Imperial Advanced Computing"),
    ("blank", "", ""),
    ("meta", "Previously", "PhoneHost — AI Host for Restaurants"),
    ("meta", "Open Source", "toks, agentdictate"),
    ("meta", "Following", "Bun · GPUI · SpacetimeDB · Omarchy"),
    ("meta", "Principle", "Keep it simple, stupid."),
    ("meta", "Offline", "Poker · Gym"),
    ("blank", "", ""),
    ("section", "Contact", ""),
    ("meta", "GitHub", "github.com/Luzivog"),
    ("meta", "Website", "thomas-fairhurst.com"),
    ("meta", "LinkedIn", "linkedin.com/in/thomas-fht"),
    ("meta", "X", "x.com/luzivog"),
    ("blank", "", ""),
    ("section", "Projects", ""),
    ("meta", "Leadlord", "Compliant marketing campaigns"),
    ("meta", "PhoneHost", "AI Host for Restaurants"),
    ("meta", "toks", "Local AI coding usage tracker"),
    ("meta", "agentdictate", "Native Linux voice dictation"),
)

ROW_COUNT = 23
ROW_START = 30
ROW_HEIGHT = 20
RIGHT_X = 450
RIGHT_WIDTH = 56


def separator_tail(label: str) -> str:
    return " -" + "—" * max(1, RIGHT_WIDTH - len(label) - 2)


def metadata_svg() -> str:
    rendered: list[str] = []
    for index, (kind, label, value) in enumerate(RIGHT_ROWS):
        y = ROW_START + index * ROW_HEIGHT
        if kind == "prompt":
            rendered.append(
                f'<tspan x="{RIGHT_X}" y="{y}" class="value">{html.escape(label)}</tspan>'
                f'<tspan class="cc"> › </tspan>'
                f"{html.escape(value)}"
            )
        elif kind == "section":
            heading = f"- {label}"
            rendered.append(
                f'<tspan x="{RIGHT_X}" y="{y}">{html.escape(heading)}</tspan>'
                f"{separator_tail(heading)}"
            )
        elif kind == "blank":
            rendered.append(f'<tspan x="{RIGHT_X}" y="{y}" class="cc">. </tspan>')
        else:
            fixed_length = len(". ") + len(label) + len(":") + len(value) + 2
            dots = "." * max(1, RIGHT_WIDTH - fixed_length)
            rendered.append(
                f'<tspan x="{RIGHT_X}" y="{y}" class="cc">. </tspan>'
                f'<tspan class="key">{html.escape(label)}</tspan>:'
                f'<tspan class="cc"> {dots} </tspan>'
                f'<tspan class="value">{html.escape(value)}</tspan>'
            )
    return "\n".join(rendered)


def load_portrait(path: Path) -> bytes:
    encoded = path.read_bytes()
    with Image.open(path) as source:
        source.load()
        if source.format != "PNG":
            raise ValueError(f"{path} must be a PNG image")
    return encoded


def profile_svg(portrait_path: Path) -> str:
    if len(RIGHT_ROWS) != ROW_COUNT:
        raise ValueError(f"Metadata must occupy exactly {ROW_COUNT} terminal rows")

    portrait_bytes = load_portrait(portrait_path)
    portrait = base64.b64encode(portrait_bytes).decode("ascii")
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/render_profile.py. -->
<svg xmlns="http://www.w3.org/2000/svg" font-family="ConsolasFallback,Consolas,'DejaVu Sans Mono',monospace" width="1006px" height="530px" font-size="16px" role="img" aria-labelledby="title description">
  <title id="title">Thomas Fairhurst — GitHub profile</title>
  <desc id="description">Co-founder and CTO at Leadlord. Open-source author of toks and agentdictate. Following Bun, GPUI, SpacetimeDB, and Omarchy. Keep it simple, stupid. Plays poker and works out.</desc>
  <style>
    @font-face {{
      src: local('Consolas'), local('Consolas Bold');
      font-family: 'ConsolasFallback';
      font-display: swap;
      -webkit-size-adjust: 109%;
      size-adjust: 109%;
    }}
    .key {{ fill: {PALETTE.key}; font-weight: 600; }}
    .value {{ fill: {PALETTE.value}; }}
    .cc {{ fill: {PALETTE.connector}; }}
    text, tspan {{ white-space: pre; }}
  </style>
  <rect width="1006px" height="530px" fill="{PALETTE.background}" rx="15"/>
  <image x="5" y="10" width="440" height="510" preserveAspectRatio="xMidYMid meet" href="data:image/png;base64,{portrait}"/>
  <text x="{RIGHT_X}" y="{ROW_START}" fill="{PALETTE.text}">
  {metadata_svg()}
  </text>
</svg>
'''


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--portrait", default=Path("assets/portrait-ascii.png"), type=Path)
    parser.add_argument("--output", default=Path("assets/profile.svg"), type=Path)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(profile_svg(args.portrait), encoding="utf-8")


if __name__ == "__main__":
    main()
